### ISSUE TITLE
Can't find .env file in current working directory with default config on Windows

### ISSUE THREAD

**Issue by Playacem** [cdimascio/dotenv-kotlin#11]
The default configuration fails to load on Windows, even though the `.env` file exists.

**Expected behaviour**
`Dotenv env = Dotenv.load()` loads fine.

**Actual behaviour**
Throws an "missing .env file" exception.

**Workaround**
`Dotenv env = Dotenv.configure().directory(".").load()`

**Comment by cdimascio** [comment]
@Playacem I've modified the default path to "./", rather than "". Based on your description I'm hoping this resolve the Windows issue. Hoping you might verify once again

see this change: https://github.com/cdimascio/java-dotenv/blob/master/src/main/kotlin/io/github/cdimascio/dotenv/Dotenv.kt#L49

assuming it looks good, i'll generate a new release

**Comment by Playacem** [comment]
Sadly the fix does not seem to fix the issue. 

Initialization code: `Dotenv ENV = Dotenv.configure().load();`
The .env file exists in the working directory (`E:\Dev\Project`)

Exception: 
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at playacem.Main.setupLogging(Main.java:63)
	at playacem.Main.main(Main.java:19)
Caused by: io.github.cdimascio.dotenv.DotEnvException: Could not find /.env on the classpath
	at io.github.cdimascio.dotenv.internal.ClasspathHelper.loadFileFromClasspath(ClassPathHelper.kt:32)
	at io.github.cdimascio.dotenv.internal.DotenvReader.read(DotenvReader.kt:34)
	at io.github.cdimascio.dotenv.internal.DotenvParser.parse(DotenvParser.kt:22)
	at io.github.cdimascio.dotenv.DotenvBuilder.load(Dotenv.kt:52)
	at playacem.util.env.Config.<clinit>(Config.java:9)
	... 2 more
	Suppressed: io.github.cdimascio.dotenv.DotEnvException: Could not find \.env on the file system (working directory: E:\Dev\Project)
		at io.github.cdimascio.dotenv.internal.DotenvReader.read(DotenvReader.kt:38)
		... 5 more
```

I build the current master branch and used `mvn install` to install into my local m2 repository.

**Comment by cdimascio** [comment]
Thanks @Playacem. Bummer. Looks like i need to set up a windows VM to explore this. If you feel comfortable, feel free to dig in as well. I'm happy to accept a PR.

**Comment by Playacem** [comment]
@cdimascio I just realized that I did not test the change properly. My IDE did not recognize the change of versions properly and used the old version of java-dotenv. 

The fix does indeed work!

**Comment by cdimascio** [comment]
Fantastic! Thanks so much for helping me with the resolution.

**Comment by cdimascio** [comment]
i'll roll a new version shortly
