### ISSUE TITLE
Directory configuration not working correctly

### ISSUE THREAD

**Issue by darlandc1998** [cdimascio/dotenv-kotlin#35]
I put the .env file inside / src / main / resources but still still giving the following error when I run .jar.

```java
Caused by: io.github.cdimascio.dotenv.DotEnvException: Could not find ./.env on the classpath
	at io.github.cdimascio.dotenv.internal.ClasspathHelper.loadFileFromClasspath(ClassPathHelper.kt:37)
	at io.github.cdimascio.dotenv.internal.DotenvReader.read(DotenvReader.kt:36)
	at io.github.cdimascio.dotenv.internal.DotenvParser.parse(DotenvParser.kt:26)
	at io.github.cdimascio.dotenv.DotenvBuilder.load(Dotenv.kt:119)
	at io.github.cdimascio.dotenv.Dotenv$Instance.load(Dotenv.kt:32)
	at io.github.cdimascio.dotenv.Dotenv.load(Dotenv.kt)
	at com.org.teammove.utils.UtilDotenv.getEnv(UtilDotenv.java:10)
	at com.org.teammove.utils.UtilConectorPostgreSQL.getHOST_LOGIN(UtilConectorPostgreSQL.java:8)
	at com.org.teammove.autenticacao.AutenticacaoDatabaseConfig.dataSource(AutenticacaoDatabaseConfig.java:15)
	at com.org.teammove.autenticacao.AutenticacaoDatabaseConfig$$EnhancerBySpringCGLIB$$c94cd15a.CGLIB$dataSource$0(<generated>)
	at com.org.teammove.autenticacao.AutenticacaoDatabaseConfig$$EnhancerBySpringCGLIB$$c94cd15a$$FastClassBySpringCGLIB$$e0a583b5.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361)
	at com.org.teammove.autenticacao.AutenticacaoDatabaseConfig$$EnhancerBySpringCGLIB$$c94cd15a.dataSource(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 50 more

```

Version used is 5.1.1

I ended up viewing the other issues created, but none solved my problem.

**Comment by darlandc1998** [comment]
Problem solved. While searching for environment variables had to add the following code 
```java 
private static Dotenv getDotenvPadrao(){
        return Dotenv.configure().directory("/").load();
}
```

The secret was to add ``.directory ("/") ``

**Comment by Aditya94A** [comment]
Thanks @darlandc1998 for responding with the solution as well!

I was stuck on this for hours, trying to deploy a ktor server and this got everything working.

@cdimascio This should be prominently featured somewhere, maybe under FAQs.

**Comment by cdimascio** [comment]
@AdityaAnand1 would you be interested in adding something to the FAQ/README?

Also, could you provide an example of your Ktor app. I'd like to also reproduce this myself. 
I'm wondering if this is actually a bug and something that java-dotenv can be made to handle better. any thoughts on your end?
